Feature/CRTCMD for streamfiles
halcyon-tech/code-for-ibmi pull request #115
Opened 2021-03-18 23:51 UTC by chrjorgensen

### Changes

This change adds CRTCMD for streamfiles.
It also fixes the CRTCMD commands for members (misspelled variable).

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in the README

2021-03-19 00:11 UTC, chrjorgensen commented
Is it correct that new default actions will not be added to the actions after the extension has been installed? That they will only be active for new installs?

2021-03-19 13:52 UTC, worksofliam commented
Thanks @chrjorgensen! This is great.

2021-03-19 13:54 UTC, worksofliam requested changes
Please see my notes. Thanks!

2021-03-19 13:54 UTC, worksofliam commented on package.json
> +							"command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPNLIB/&OPENMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(ALLOW(*BPGM *IPGM *BMOD *IMOD) ) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
Should `&OPENMBRC`be `&OPENMBR`?

2021-03-19 13:54 UTC, worksofliam commented on package.json
> +							"command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPNLIB/&OPENMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
Should `&OPENMBRC` be `&OPENMBR`?

2021-03-19 13:54 UTC, worksofliam commented on package.json
> +							"command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAMEC) SRCSTMF('&FULLPATH') OPTION(*EVENTF)"
`&NAMEC` here probably should be `&NAME` right?

2021-03-19 13:54 UTC, worksofliam commented on package.json
> +							"command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAMEC) SRCSTMF('&FULLPATH') ALLOW(*BPGM *IPGM *BMOD *IMOD *BREXX *IREXX) OPTION(*EVENTF)"
`&NAMEC` here probably should be `&NAME` right?

2021-03-19 16:31 UTC, chrjorgensen commented on package.json
> +							"command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPNLIB/&OPENMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(ALLOW(*BPGM *IPGM *BMOD *IMOD) ) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
It depends - the "C" was already there, probably because the person originally creating the command has a naming standard for command processing programs having the name of the command with an appended "C".

I didn't want to change this - however, I agree with your opinion... since it is also my standard: No appended "C".
So I'll be happy to remove the "C".

2021-03-19 16:32 UTC, chrjorgensen commented on package.json
> +							"command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPNLIB/&OPENMBRC) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
It depends - the "C" was already there, probably because the person originally creating the command has a naming standard for command processing programs having the name of the command with an appended "C".

I didn't want to change this - however, I agree with your opinion... since it is also my standard: No appended "C".
So I'll be happy to remove the "C".

2021-03-19 16:32 UTC, chrjorgensen commented on package.json
> +							"command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAMEC) SRCSTMF('&FULLPATH') OPTION(*EVENTF)"
It depends - the "C" was already there, probably because the person originally creating the command has a naming standard for command processing programs having the name of the command with an appended "C".

I didn't want to change this - however, I agree with your opinion... since it is also my standard: No appended "C".
So I'll be happy to remove the "C".

2021-03-19 16:32 UTC, chrjorgensen commented on package.json
> +							"command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAMEC) SRCSTMF('&FULLPATH') ALLOW(*BPGM *IPGM *BMOD *IMOD *BREXX *IREXX) OPTION(*EVENTF)"
It depends - the "C" was already there, probably because the person originally creating the command has a naming standard for command processing programs having the name of the command with an appended "C".

I didn't want to change this - however, I agree with your opinion... since it is also my standard: No appended "C".
So I'll be happy to remove the "C".

2021-03-19 22:22 UTC, chrjorgensen commented
The name for the command processing program on CRTCMD commands has been changed to the same as the command itself - no more "C" appended.

2021-03-20 14:56 UTC, worksofliam approved these changes
Looking good!!!

2021-03-20 14:56 UTC, worksofliam commented
Thanks @chrjorgensen - this is great. Thanks for your work!

2021-03-23 13:25 UTC, merged