Added TCP Port setting for SSH.
halcyon-tech/code-for-ibmi pull request #3
Opened 2021-02-21 17:04 UTC by richardschoen

2021-02-21 17:19 UTC, richardschoen commented
Also change temp file name from /tmp/randomvalue to /tmp/vscodetemp-randomvalue so they can be cleaned up easily. Perhaps home directory makes sense at some point but at least they can clean their temp dirs easier with this naming.

2021-02-21 23:53 UTC, worksofliam approved these changes
LGTM. Need to do some testing but then I'll give it a whirl.

2021-02-21 23:53 UTC, worksofliam commented on src/api/IBMi.js
> +   * @param {{host: string, port: string, username: string, password: string, keepaliveInterval?: number}} connectionObject
Why is port a string? Shouldn't it b a number?

2021-02-22 00:18 UTC, worksofliam requested changes
After the user is done in the webview, the `port` needs to be converted to a number.

Please make those changes and I can review again.

2021-02-22 00:18 UTC, worksofliam commented on package.json
> +								"type": "string",
This should be a number.

2021-02-22 01:11 UTC, richardschoen commented on src/api/IBMi.js
> +   * @param {{host: string, port: string, username: string, password: string, keepaliveInterval?: number}} connectionObject
I guess, but it works. Must get auto-converted.

2021-02-22 01:16 UTC, worksofliam commented on src/api/IBMi.js
> +   * @param {{host: string, port: string, username: string, password: string, keepaliveInterval?: number}} connectionObject
It may work, but I am trying my best to write the easier code to understand + eslint is moaning at me! 
![image](https://user-images.githubusercontent.com/3708366/108645694-b0c16680-7481-11eb-8bb2-e8e1564bc50c.png)

2021-02-22 01:24 UTC, richardschoen commented
Updates pushed

2021-02-22 16:15 UTC, closed without merging

2021-02-22 16:15 UTC, worksofliam commented
Accidently put it onto another branch.