Fix CPYTOIMPF for different default
halcyon-tech/code-for-ibmi pull request #33
Opened 2021-02-25 17:47 UTC by dariocs

### Changes

Description of change here.

### Checklist

* [ x ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in the README

2021-02-25 23:12 UTC, worksofliam commented
@dariocs Is this PR finished?

2021-02-26 08:05 UTC, dariocs commented
Yes , thanks

2021-02-26 14:04 UTC, worksofliam commented
@dariocs Would you mind updating the text of the change in your PR and also complex the checklist?

Thanks!

2021-03-01 17:00 UTC, dariocs commented
@worksofliam 
Hi Liam , 
I have done , I'm not so smart with git .. I'm beginner ... 
Thanks

2021-03-01 19:33 UTC, worksofliam requested changes
Please see my comments and make changes where necessary. When you are ready, please request a review again 😄

2021-03-01 19:33 UTC, worksofliam commented on src/api/IBMiContent.js
> +          `CPYTOSTMF FROMMBR('${path}') TOSTMF('${tempRmt}') STMFOPT(*REPLACE) STMFCCSID(1208) FLDDLM(',') DECPNT(*PERIOD)`, '.'
Sadly this change is invalid.

`FLDDLM` and `DECPNT` are not valid commands on [CPYTOSTMF](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/cl/cpytostmf.htm). These will need to be removed before I can merge this commit.

2021-03-01 19:33 UTC, worksofliam commented on src/api/IBMiContent.js
> +        "') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) ",
Looks good to me!

2021-03-01 19:43 UTC, worksofliam commented on src/api/IBMiContent.js
> +          `CPYTOSTMF FROMMBR('${path}') TOSTMF('${tempRmt}') STMFOPT(*REPLACE) STMFCCSID(1208) FLDDLM(',') DECPNT(*PERIOD)`, '.'
```
PD0043: Keyword FLDDLM not valid for this command.
CPD0043: Keyword DECPNT not valid for this command.
CPF0006: Errors occurred in command.
```

2021-03-01 20:59 UTC, worksofliam approved these changes

2021-03-01 21:00 UTC, worksofliam commented
@dariocs I have retested and it's all looking good.

Thank you for your contribution!!

2021-03-01 21:00 UTC, merged