Add File Picker for SSH Key
halcyon-tech/code-for-ibmi pull request #94
Opened 2021-03-10 20:34 UTC by priceaj

### Changes

I've expanded on the work done by @onewheelonly and added a file picker for the SSH Key.

### Checklist

* [X] have tested my change - with caveats (I have not tested the actual connection works as I don't have SSH Keys set up on PUB400.com)
* [X ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [X] have added myself to the contributors' list in the README

2021-03-10 20:45 UTC, onewheelonly commented
Yup, I can give this a try on Windows (at some point). Thanks for this, Aaron!

2021-03-10 21:16 UTC, worksofliam commented
This is awesome. I will give the mac change a go.

2021-03-10 21:28 UTC, worksofliam commented
Looking good on a mac!

@onewheelonly let me know how it is for Windows and we will merge.

2021-03-10 21:54 UTC, priceaj commented on src/api/CustomUI.js
> +                          reader.readAsText(file);
I realise I am actually reading the file here, and I could have done this more efficiently, but I wanted to leave scope to enable me to read the key into the VSCode secret storage and use it from there

2021-03-10 21:56 UTC, worksofliam commented on src/api/CustomUI.js
> +                          reader.readAsText(file);
@priceaj You're reading the file but not assigning it anywhere. Are you planning to remove this piece of code? Or something else with it?

2021-03-10 21:57 UTC, worksofliam commented on src/api/CustomUI.js
> +                          reader.readAsText(file);
Wait. I now see it's triggering an event when it is read - except it's still passing the path back in the data.

2021-03-10 21:57 UTC, priceaj commented on src/api/CustomUI.js
> +                      let input = VirtualField.shadowRoot.querySelector("input");
this isn't great, but the framework doesn't expose the "files" attribute of the underlying input box

2021-03-10 22:01 UTC, worksofliam commented
@priceaj 

```js
                          let reader = new FileReader();
                          reader.addEventListener("load", () => {
                            console.log(file.path);
                            document.getElementById(e.target.id).setAttribute("value", file.path)   
                          });
                          reader.readAsText(file);
```

What's the point of reading the file? Perhaps you should just pass the selected path back (like you are already doing)

2021-03-10 22:01 UTC, priceaj commented on src/api/CustomUI.js
> +                          reader.readAsText(file);
yeah, It's there so that the feature can be expanded to read the content of the Private Key file, and store it in the VSCode secret storage (along with any passwords)... and I've just spotted a console.log I didn't remove!

2021-03-10 22:14 UTC, worksofliam commented on src/api/CustomUI.js
> +                          reader.readAsText(file);
@priceaj I will wait for another push from you before I do any more :)

2021-03-10 22:15 UTC, worksofliam requested changes
* Are you planning on removing the `readAsText` and just passing back the path?
* Please remove your console.log

2021-03-10 22:15 UTC, worksofliam commented on src/api/CustomUI.js
> +                            console.log(file.path);
Naughty

2021-03-10 22:54 UTC, priceaj commented on src/api/CustomUI.js
> +                            console.log(file.path);
I have removed the console.log statement. 

I wasn't intending to remove the reading of the file, mainly because:
1. I've left it there for a future (hopefully imminent) change to read the key and pass through to node-ssh directly as a raw string (as per the commented example https://github.com/steelbrain/node-ssh#example)
2. The change gives me scope to read the key and store the ssh-key in the VSCode secret storage which should be safer than leaving an unprotected private key file sat on the file system with a plain text pointer to it in the VSCode settings
3. It leaves an obvious jumping off point if anyone else wants to add another file picker into the UI and return the content rather than the path 
4. The reason I am reading the path into the value attribute of the virtual DOM field is that by default its gets a value of C:\fakepath\filename.ppk (for security) and I am overriding that security to align with current functionality, but adding the convenience of being able to choose a file rather than having to paste/type a file path. I'd like to read the content of the file so that this workaround isn't necessary. 
5. As far as I can tell it doesn't create any bugs or overhead, even if the file is deleted after it's selected

2021-03-10 23:17 UTC, worksofliam commented on src/api/CustomUI.js
> +                            console.log(file.path);
Thanks for all this detailed info!

2021-03-10 23:18 UTC, worksofliam commented
Everything is in order. I just would like @onewheelonly to confirm it works for them as well and we shall go forward with the merge.

2021-03-11 00:15 UTC, onewheelonly commented
Everything looks fine on the Windows side 👍

2021-03-11 00:43 UTC, worksofliam approved these changes

2021-03-11 00:44 UTC, merged